"use client";

import { Download, FileText } from "lucide-react";
import { GlassCard } from "@/components/platform/cards";
import { SeverityBadge } from "@/components/platform/badges";
import { reports } from "@/lib/demo-data";

type RailReport = {
  title: string;
  type: string;
  status: string;
  owner: string;
  updated: string;
};

function generateRailReport(report: RailReport) {
  const generatedAt = new Date().toLocaleString();

  const reportHtml = `
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<title>${report.title}</title>
<style>
  body {
    font-family: Arial, Helvetica, sans-serif;
    margin: 40px;
    color: #172033;
    line-height: 1.6;
  }

  .header {
    border-bottom: 4px solid #1769aa;
    padding-bottom: 18px;
    margin-bottom: 28px;
  }

  .brand {
    font-size: 30px;
    font-weight: 800;
    color: #0b4f82;
  }

  .subtitle {
    font-size: 15px;
    color: #526477;
  }

  h1 {
    font-size: 25px;
    margin-top: 30px;
  }

  h2 {
    color: #0b4f82;
    margin-top: 28px;
    border-bottom: 1px solid #d9e2ec;
    padding-bottom: 6px;
  }

  .meta {
    width: 100%;
    border-collapse: collapse;
    margin: 20px 0 30px;
  }

  .meta td {
    border: 1px solid #d7dee8;
    padding: 10px 12px;
  }

  .meta td:first-child {
    font-weight: 700;
    width: 30%;
    background: #f5f8fb;
  }

  .evidence {
    background: #f5f8fb;
    border-left: 4px solid #1769aa;
    padding: 15px 18px;
    margin: 15px 0;
  }

  .warning {
    background: #fff8e8;
    border-left: 4px solid #d99b19;
    padding: 15px 18px;
  }

  .footer {
    margin-top: 50px;
    border-top: 1px solid #d7dee8;
    padding-top: 15px;
    font-size: 12px;
    color: #6b7785;
  }

  @media print {
    body {
      margin: 18mm;
    }
  }
</style>
</head>

<body>

<div class="header">
  <div class="brand">ForgeMind Rail</div>
  <div class="subtitle">
    Evidence-Grounded Railway Asset Intelligence Platform
  </div>
</div>

<h1>${report.title}</h1>

<table class="meta">
  <tr>
    <td>Report Type</td>
    <td>${report.type}</td>
  </tr>
  <tr>
    <td>Status</td>
    <td>${report.status}</td>
  </tr>
  <tr>
    <td>Responsible Function</td>
    <td>${report.owner}</td>
  </tr>
  <tr>
    <td>Data Updated</td>
    <td>${report.updated}</td>
  </tr>
  <tr>
    <td>Generated</td>
    <td>${generatedAt}</td>
  </tr>
</table>

<h2>1. Executive Summary</h2>

<p>
This report has been generated by ForgeMind Rail from the railway
asset intelligence environment. It consolidates asset condition,
inspection history, maintenance evidence, operational indicators,
risk information and engineering records to support structured
railway maintenance and operational review.
</p>

<h2>2. Railway Asset Intelligence</h2>

<div class="evidence">
<strong>Primary asset domains:</strong><br/>
Track sections, turnouts, signalling systems, point machines,
bridge structures, wayside monitoring systems, track recording
systems and electrification assets.
</div>

<p>
ForgeMind Rail correlates railway asset registers with inspection,
maintenance and operational evidence so that recurring conditions
can be reviewed against historical records rather than assessed
from isolated observations.
</p>

<h2>3. Condition and Risk Review</h2>

<p>
Risk indicators are generated from available inspection findings,
reliability information, condition history and evidence completeness.
High-risk conditions require engineering review before maintenance
or operational actions are finalized.
</p>

<h2>4. Inspection Evidence</h2>

<ul>
  <li>Rail inspection and geometry records</li>
  <li>Turnout and point-machine inspection history</li>
  <li>Signalling maintenance evidence</li>
  <li>Bridge structural inspection findings</li>
  <li>Operational usage and cumulative tonnage records</li>
  <li>Track-possession and worksite safety evidence</li>
</ul>

<h2>5. Maintenance Intelligence</h2>

<p>
Maintenance recommendations should consider recurring defects,
inspection trends, previous interventions and outstanding evidence.
ForgeMind Rail is intended to support engineering review and does
not autonomously authorize maintenance execution.
</p>

<h2>6. Root Cause Analysis Support</h2>

<p>
Where recurring defects are identified, ForgeMind Rail correlates
available evidence to highlight likely contributing factors and
support structured root-cause investigation. Findings should be
validated by qualified railway engineering personnel before closure.
</p>

<h2>7. Recommended Actions</h2>

<ol>
  <li>Review current inspection evidence for the affected railway asset.</li>
  <li>Compare present findings with historical condition trends.</li>
  <li>Verify outstanding maintenance and safety documentation.</li>
  <li>Escalate repeated or high-risk findings for engineering review.</li>
  <li>Record approved corrective and preventive actions.</li>
</ol>

<h2>8. Evidence Governance</h2>

<div class="warning">
<strong>Human Review Required</strong><br/>
ForgeMind Rail provides evidence-backed decision support.
Final safety, maintenance, inspection and operational decisions
remain with authorized railway personnel.
</div>

<h2>9. Report Status</h2>

<p>
<strong>${report.status}</strong>
</p>

<div class="footer">
ForgeMind Rail · Railway Intelligence Report<br/>
Generated ${generatedAt}<br/>
Evidence-grounded decision support — human authorization required.
</div>

</body>
</html>
`;

  const blob = new Blob([reportHtml], {
    type: "text/html;charset=utf-8"
  });

  const url = URL.createObjectURL(blob);

  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download =
    report.title
      .replace(/[^a-zA-Z0-9]+/g, "_")
      .replace(/^_+|_+$/g, "") + ".html";

  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);

  URL.revokeObjectURL(url);
}

export default function ReportsPage() {
  return (
    <div className="grid gap-5">
      <div>
        <h1 className="text-3xl font-black">
          Rail Intelligence Report Center
        </h1>

        <p className="mt-2 text-slate-400">
          Generate railway RCA reports, inspection summaries,
          compliance evidence packages, executive risk summaries,
          and preventive maintenance reports.
        </p>
      </div>

      <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        {reports.map((report) => (
          <GlassCard key={report.title}>
            <FileText className="mb-4 text-cyan-300" />

            <h2 className="font-bold">
              {report.title}
            </h2>

            <p className="mt-1 text-sm text-slate-400">
              {report.type}
            </p>

            <div className="mt-4">
              <SeverityBadge
                value={
                  report.status === "Ready"
                    ? "Approved"
                    : "Needs Review"
                }
              />
            </div>

            <p className="mt-4 text-sm text-slate-400">
              {report.owner} · {report.updated}
            </p>

            <button
              type="button"
              onClick={() => generateRailReport(report)}
              className="mt-5 inline-flex items-center gap-2 rounded-xl bg-white/10 px-4 py-2 text-sm transition hover:bg-white/15"
            >
              <Download size={15} />
              Download Report
            </button>
          </GlassCard>
        ))}
      </section>

      <GlassCard>
        <h2 className="font-bold">
          Report Governance
        </h2>

        <p className="mt-2 text-sm leading-6 text-slate-400">
          Generated reports consolidate ForgeMind Rail evidence for
          engineering review. They provide decision support only;
          maintenance, safety and operational authorization remains
          with qualified railway personnel.
        </p>
      </GlassCard>
    </div>
  );
}